# Generated by Django 5.1.15 on 2026-04-25 04:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterIKU",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kode_iku", models.CharField(db_index=True, max_length=50)),
                ("tujuan", models.TextField(blank=True, default="")),
                ("sasaran", models.TextField(blank=True, default="")),
                (
                    "indikator",
                    models.TextField(
                        blank=True, default="", help_text="Nama indikator IKU"
                    ),
                ),
                (
                    "jenis_iku",
                    models.CharField(
                        choices=[("IKU", "IKU Utama"), ("PROKSI", "Proksi")],
                        default="IKU",
                        max_length=20,
                    ),
                ),
                (
                    "jenis_periode",
                    models.CharField(
                        choices=[("TAHUNAN", "Tahunan"), ("TRIWULANAN", "Triwulanan")],
                        default="TRIWULANAN",
                        max_length=20,
                    ),
                ),
                (
                    "jenis_persen",
                    models.BooleanField(
                        default=True, help_text="True jika satuan persen"
                    ),
                ),
                ("satuan", models.CharField(blank=True, default="", max_length=50)),
                ("has_proxy", models.BooleanField(default=False)),
                (
                    "proxy_x_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "proxy_y_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("cells", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name_plural": "Master IKU",
                "ordering": ["kode_iku"],
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("VIEWER", "Viewer"),
                            ("OPERATOR", "Operator"),
                        ],
                        default="OPERATOR",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="FRAEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pulled_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Semua nilai PULL_ONLY dari GSheet (target, capaian, alokasi, PKO, dll)",
                    ),
                ),
                ("kendala", models.TextField(blank=True, default="")),
                ("solusi", models.TextField(blank=True, default="")),
                ("rtl", models.TextField(blank=True, default="")),
                ("pic_rtl", models.CharField(blank=True, default="", max_length=255)),
                (
                    "batas_waktu_rtl",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "link_bukti_kinerja",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "link_bukti_tl_sebelumnya",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "link_solusi",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("realisasi", models.CharField(blank=True, default="", max_length=100)),
                (
                    "proksi_x_realisasi",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "proksi_y_realisasi",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("is_done", models.BooleanField(default=False)),
                (
                    "is_dirty",
                    models.BooleanField(
                        default=False,
                        help_text="TRUE jika sudah di-save operator. Memblokir PULL overwrite.",
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pic_tim_kerja",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "iku",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry",
                        to="pikas_app.masteriku",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "FRA Entries",
            },
        ),
        migrations.CreateModel(
            name="PeriodeKertasKerja",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tahun",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2020)]
                    ),
                ),
                (
                    "triwulan",
                    models.IntegerField(
                        choices=[(1, "TW I"), (2, "TW II"), (3, "TW III"), (4, "TW IV")]
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(
                        help_text="Nama sheet di Google Spreadsheet, misal: 2026Q1",
                        max_length=100,
                    ),
                ),
                (
                    "config_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Master JSON config: daftar IKU beserta mapping koordinat cell GSheet.",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Jika True, Operator tidak bisa submit/edit FRA.",
                    ),
                ),
                (
                    "is_configured",
                    models.BooleanField(
                        default=False,
                        help_text="True jika config_json sudah diisi dan PULL sudah dilakukan.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Periode Kertas Kerja",
                "ordering": ["-tahun", "-triwulan"],
                "unique_together": {("tahun", "triwulan")},
            },
        ),
        migrations.AddField(
            model_name="masteriku",
            name="periode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ikus",
                to="pikas_app.periodekertaskerja",
            ),
        ),
        migrations.CreateModel(
            name="AppConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gsheet_id",
                    models.CharField(
                        help_text="ID unik dari URL Google Spreadsheet (satu untuk semua periode).",
                        max_length=255,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_periode",
                    models.ForeignKey(
                        blank=True,
                        help_text="Periode yang sedang aktif untuk Dashboard & Operator.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pikas_app.periodekertaskerja",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "App Config",
            },
        ),
        migrations.AlterUniqueTogether(
            name="masteriku",
            unique_together={("periode", "kode_iku")},
        ),
    ]
