# Generated by Django 5.1.15 on 2026-04-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pikas_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="masteriku",
            options={
                "ordering": ["kode_indikator"],
                "verbose_name_plural": "Master IKU",
            },
        ),
        migrations.RenameField(
            model_name="masteriku",
            old_name="kode_iku",
            new_name="kode_indikator",
        ),
        migrations.AlterUniqueTogether(
            name="masteriku",
            unique_together={("periode", "kode_indikator")},
        ),
        migrations.AddField(
            model_name="masteriku",
            name="kode_sasaran",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="masteriku",
            name="kode_tujuan",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
