# Generated by Django 5.1.15 on 2026-04-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pikas_app", "0002_alter_masteriku_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="masteriku",
            name="target",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
