# Generated by Django 5.1.15 on 2026-04-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pikas_app", "0003_masteriku_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="fraentry",
            name="is_bukti_kinerja_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fraentry",
            name="is_bukti_solusi_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fraentry",
            name="is_bukti_tl_done",
            field=models.BooleanField(default=False),
        ),
    ]
