# Generated by Django 5.1.15 on 2026-04-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pikas_app", "0004_fraentry_is_bukti_kinerja_done_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fraentry",
            name="notulen",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Catatan rincian basis data (X/Y atau sumber data utama)",
            ),
        ),
    ]
