# Generated by Django 5.1.15 on 2026-05-01 02:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pikas_app", "0005_fraentry_notulen"),
    ]

    operations = [
        migrations.CreateModel(
            name="TahunKerja",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tahun",
                    models.IntegerField(
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(2020)],
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MasterRO",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kode_iku",
                    models.CharField(
                        help_text="Kode IKU yang menaungi RO ini (misal: 1.1.3.1.)",
                        max_length=50,
                    ),
                ),
                (
                    "kode_ro",
                    models.CharField(
                        help_text="Kode RO (misal: 2906 BMA 005)", max_length=50
                    ),
                ),
                ("nama_ro", models.TextField(help_text="Nama Rincian Output")),
                (
                    "daftar_kegiatan",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Daftar kegiatan (1 per baris) untuk tooltip panduan",
                    ),
                ),
                (
                    "tahun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ros",
                        to="pikas_app.tahunkerja",
                    ),
                ),
            ],
            options={
                "unique_together": {("tahun", "kode_ro")},
            },
        ),
        migrations.CreateModel(
            name="RealisasiRO",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bulan",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("konten", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "master_ro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realisasi",
                        to="pikas_app.masterro",
                    ),
                ),
            ],
            options={
                "unique_together": {("master_ro", "bulan")},
            },
        ),
    ]
